// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	device "github.com/anxiu0101/openiot-hub/api-gateway/biz/router/device"
	user "github.com/anxiu0101/openiot-hub/api-gateway/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	device.Register(r)

	user.Register(r)

}
